default: &default
  adapter: postgresql
  encoding: unicode
  host: localhost
  username: khcr
  pool: 5

development:
  <<: *default
  database: rencontredejeunesse_development

test:
  <<: *default
  database: rencontredejeunesse_test

production:
  <<: *default
  database: rencontredejeunesse_production
  username: rencontredejeunesse
  password:
